sudo: required

dist: trusty

env:
  - TEST_SUITE=lint
  - TEST_SUITE=test

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

script:
  - "npm run $TEST_SUITE"

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
